# .github/workflows/generate_gist.yml
name: Generate and Post Gist

on:
  push:
    branches:
      - main  # Run the workflow when there's a push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 */2 * * *'  # Run the workflow daily at midnight UTC

jobs:
  generate_and_post_gists:
    runs-on: ubuntu-latest

    # Define permissions only for this job
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install requests
        python3 -m pip install -e .

    - name: Generate Data
      run: |
        make clean
        ripper matches -s ncaa -o matches.csv
        ripper rpi -s ncaa -i matches.csv -o rpi.csv
        ripper elo -s ncaa -i matches.csv -o elo.csv
        ripper record -s ncaa -i matches.csv -o record.csv                
        ripper matches -s nwsl -o nwsl_matches.csv
        ripper rpi -s nwsl -i nwsl_matches.csv -o nwsl_rpi.csv
        ripper elo -s nwsl -i nwsl_matches.csv -o nwsl_elo.csv
        ripper record -s nwsl -i nwsl_matches.csv -o nwsl_record.csv

    - name: Run Python script to generate and post Gist
      run: |
        ripper post -d "Matches" --public --token ${{ secrets.GIST_PAT }} matches.csv
        ripper post -d "RPI Ratings" --public --token ${{ secrets.GIST_PAT }} --input matches.csv rpi.csv
        ripper post -d "Elo Ratings" --public --token ${{ secrets.GIST_PAT }} --input matches.csv elo.csv
        ripper post -d "Record" --public --token ${{ secrets.GIST_PAT }} --input matches.csv record.csv        
        ripper post -d "NWSL Matches" --public --token ${{ secrets.GIST_PAT }} nwsl_matches.csv
        ripper post -d "NWSL RPI Ratings" --public --token ${{ secrets.GIST_PAT }} nwsl_rpi.csv
        ripper post -d "NWSL Elo Ratings" --public --token ${{ secrets.GIST_PAT }} nwsl_elo.csv
        ripper post -d "NWSL Record" --public --token ${{ secrets.GIST_PAT }} nwsl_record.csv
