# .github/workflows/generate_gist.yml
name: Generate and Post Gist

on:
  push:
    branches:
      - main  # Run the workflow when there's a push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 */2 * * *'  # Run the workflow daily at midnight UTC

jobs:
  generate_and_post_gists:
    runs-on: ubuntu-latest

    # Define permissions only for this job
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install requests
        python3 -m pip install -e .

    - name: Generate Data
      run: |
        make clean
        ripper matches -o matches.csv
        ripper rpi -o rpi.csv
        ripper elo -o elo.csv
        ripper record -o record.csv

    - name: Verify GitHub token permissions
      run: |
        echo "Checking GitHub token permissions..."
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/gists

    - name: Run Python script to generate and post Gist
      run: |
        ripper post --description="Matches" --public --token=${{ secrets.GIST_PAT }} matches.csv
        ripper post --description="RPI Ratings" --public --token=${{ secrets.GIST_PAT }} rpi.csv
        ripper post --description="Elo Ratings" --public --token=${{ secrets.GIST_PAT }} elo.csv
        ripper post --description="Record" --public --token=${{ secrets.GIST_PAT }} record.csv
