name: Matches Workflow

on:
  push:
    branches:
      - main  # Run the workflow when there's a push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 * * * *'  # Run the workflow every hour

jobs:
  run_matches:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install click requests tenacity numpy
        python3 -m pip install -e .

    - name: Run Matches Script
      run: |
        python3 matches.py get --gender female --division d1 --from-date 2024-08-15
        ripper post -d "Women's DI Matches" --public --token ${{ secrets.GIST_PAT }} female_d1_matches.csv
        
        python3 matches.py get --gender female --division d2 --from-date 2024-08-15
        ripper post -d "Women's DII Matches" --public --token ${{ secrets.GIST_PAT }} female_d2_matches.csv
        
        python3 matches.py get --gender female --division d3 --from-date 2024-08-15
        ripper post -d "Women's DIII Matches" --public --token ${{ secrets.GIST_PAT }} female_d3_matches.csv
        
        python3 matches.py get --gender male --division d1 --from-date 2024-08-15
        ripper post -d "Men's DI Matches" --public --token ${{ secrets.GIST_PAT }} male_d1_matches.csv
        
        python3 matches.py get --gender male --division d2 --from-date 2024-08-15
        ripper post -d "Men's DII Matches" --public --token ${{ secrets.GIST_PAT }} male_d2_matches.csv
        
        python3 matches.py get --gender male --division d3 --from-date 2024-08-15
        ripper post -d "Men's DIII Matches" --public --token ${{ secrets.GIST_PAT }} male_d3_matches.csv
